#!/usr/bin/env bash

# Shared train_pretrain.py argument contract for local and remote launches.

RUNTIME_DEFAULTS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/runtime-defaults.sh"
# shellcheck source=/dev/null
source "$RUNTIME_DEFAULTS_FILE"

minimind_train_pretrain_args() {
    local data_path="$1"
    local save_dir="$2"

    MINIMIND_TRAIN_PRETRAIN_ARGS=(
        --epochs "${TRAIN_EPOCHS:-$GPUPOOR_DEFAULT_TRAIN_EPOCHS}"
        --batch_size "${TRAIN_BATCH_SIZE:-$GPUPOOR_DEFAULT_TRAIN_BATCH_SIZE}"
        --learning_rate "${TRAIN_LEARNING_RATE:-$GPUPOOR_DEFAULT_TRAIN_LEARNING_RATE}"
        --accumulation_steps "${TRAIN_ACCUMULATION_STEPS:-$GPUPOOR_DEFAULT_TRAIN_ACCUMULATION_STEPS}"
        --num_workers "${TRAIN_NUM_WORKERS:-$GPUPOOR_DEFAULT_TRAIN_NUM_WORKERS}"
        --grad_clip "${TRAIN_GRAD_CLIP:-$GPUPOOR_DEFAULT_TRAIN_GRAD_CLIP}"
        --hidden_size "${TRAIN_HIDDEN_SIZE:-$GPUPOOR_DEFAULT_TRAIN_HIDDEN_SIZE}"
        --num_hidden_layers "${TRAIN_NUM_HIDDEN_LAYERS:-$GPUPOOR_DEFAULT_TRAIN_NUM_HIDDEN_LAYERS}"
        --dropout "${TRAIN_DROPOUT:-$GPUPOOR_DEFAULT_TRAIN_DROPOUT}"
        --vocab_size "${TRAIN_VOCAB_SIZE:-$GPUPOOR_DEFAULT_TRAIN_VOCAB_SIZE}"
        --flash_attn "${TRAIN_FLASH_ATTN:-$GPUPOOR_DEFAULT_TRAIN_FLASH_ATTN}"
        --num_attention_heads "${TRAIN_NUM_ATTENTION_HEADS:-$GPUPOOR_DEFAULT_TRAIN_NUM_ATTENTION_HEADS}"
        --num_key_value_heads "${TRAIN_NUM_KEY_VALUE_HEADS:-$GPUPOOR_DEFAULT_TRAIN_NUM_KEY_VALUE_HEADS}"
        --hidden_act "${TRAIN_HIDDEN_ACT:-$GPUPOOR_DEFAULT_TRAIN_HIDDEN_ACT}"
        --intermediate_size "${TRAIN_INTERMEDIATE_SIZE:-$GPUPOOR_DEFAULT_TRAIN_INTERMEDIATE_SIZE}"
        --max_position_embeddings "${TRAIN_MAX_POSITION_EMBEDDINGS:-$GPUPOOR_DEFAULT_TRAIN_MAX_POSITION_EMBEDDINGS}"
        --rms_norm_eps "${TRAIN_RMS_NORM_EPS:-$GPUPOOR_DEFAULT_TRAIN_RMS_NORM_EPS}"
        --rope_theta "${TRAIN_ROPE_THETA:-$GPUPOOR_DEFAULT_TRAIN_ROPE_THETA}"
        --inference_rope_scaling "${TRAIN_INFERENCE_ROPE_SCALING:-$GPUPOOR_DEFAULT_TRAIN_INFERENCE_ROPE_SCALING}"
        --max_seq_len "${MAX_SEQ_LEN:-$GPUPOOR_DEFAULT_MAX_SEQ_LEN}"
        --dtype "${TRAIN_DTYPE:-$GPUPOOR_DEFAULT_TRAIN_DTYPE}"
        --log_interval "${TRAIN_LOG_INTERVAL:-$GPUPOOR_DEFAULT_TRAIN_LOG_INTERVAL}"
        --save_interval "${TRAIN_SAVE_INTERVAL:-$GPUPOOR_DEFAULT_TRAIN_SAVE_INTERVAL}"
        --use_compile "${TRAIN_USE_COMPILE:-$GPUPOOR_DEFAULT_TRAIN_USE_COMPILE}"
        --use_moe "${TRAIN_USE_MOE:-$GPUPOOR_DEFAULT_TRAIN_USE_MOE}"
        --num_experts "${TRAIN_NUM_EXPERTS:-$GPUPOOR_DEFAULT_TRAIN_NUM_EXPERTS}"
        --num_experts_per_tok "${TRAIN_NUM_EXPERTS_PER_TOK:-$GPUPOOR_DEFAULT_TRAIN_NUM_EXPERTS_PER_TOK}"
        --moe_intermediate_size "${TRAIN_MOE_INTERMEDIATE_SIZE:-$GPUPOOR_DEFAULT_TRAIN_MOE_INTERMEDIATE_SIZE}"
        --norm_topk_prob "${TRAIN_NORM_TOPK_PROB:-$GPUPOOR_DEFAULT_TRAIN_NORM_TOPK_PROB}"
        --router_aux_loss_coef "${TRAIN_ROUTER_AUX_LOSS_COEF:-$GPUPOOR_DEFAULT_TRAIN_ROUTER_AUX_LOSS_COEF}"
        --save_weight "${TRAIN_SAVE_WEIGHT:-$GPUPOOR_DEFAULT_TRAIN_SAVE_WEIGHT}"
        --from_weight "${TRAIN_FROM_WEIGHT:-$GPUPOOR_DEFAULT_TRAIN_FROM_WEIGHT}"
        --from_resume "${TRAIN_FROM_RESUME:-$GPUPOOR_DEFAULT_TRAIN_FROM_RESUME}"
        --lr_schedule "${TRAIN_LR_SCHEDULE:-$GPUPOOR_DEFAULT_TRAIN_LR_SCHEDULE}"
        --lr_warmup_steps "${TRAIN_LR_WARMUP_STEPS:-$GPUPOOR_DEFAULT_TRAIN_LR_WARMUP_STEPS}"
        --lr_min_ratio "${TRAIN_LR_MIN_RATIO:-$GPUPOOR_DEFAULT_TRAIN_LR_MIN_RATIO}"
        --validation_split_ratio "${VALIDATION_SPLIT_RATIO:-$GPUPOOR_DEFAULT_VALIDATION_SPLIT_RATIO}"
        --validation_interval_steps "${VALIDATION_INTERVAL_STEPS:-$GPUPOOR_DEFAULT_VALIDATION_INTERVAL_STEPS}"
        --peak_tflops_per_gpu "${MLFLOW_PEAK_TFLOPS_PER_GPU:-$GPUPOOR_DEFAULT_MLFLOW_PEAK_TFLOPS_PER_GPU}"
        --time_to_target_metric "${MLFLOW_TIME_TO_TARGET_METRIC:-$GPUPOOR_DEFAULT_MLFLOW_TIME_TO_TARGET_METRIC}"
        --time_to_target_value "${MLFLOW_TIME_TO_TARGET_VALUE:-$GPUPOOR_DEFAULT_MLFLOW_TIME_TO_TARGET_VALUE}"
        --data_path "$data_path"
        --save_dir "$save_dir"
    )
}
