#!/bin/bash
# dstack/setup-config.sh — write ~/.dstack/server/config.yml with Verda backend
#
# Reads ./secrets for CliendID (note typo) and Secret.
# Idempotent: safe to run multiple times.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_FILE="$REPO_ROOT/secrets"
DSTACK_CONFIG_DIR="$HOME/.dstack/server"
DSTACK_CONFIG="$DSTACK_CONFIG_DIR/config.yml"

echo "[STEP 4] Configuring dstack server with Verda backend..."

if [ ! -f "$SECRETS_FILE" ]; then
    echo "[dstack-setup] ERROR: $SECRETS_FILE not found" >&2
    exit 1
fi

# Parse secrets — handle "CliendID" typo as well as "ClientID"
# Format:
#   Secret: <value>
#   CliendID : <value>   (note typo in Verda UI)
CLIENT_SECRET=$(grep -i '^Secret:' "$SECRETS_FILE" | head -1 | sed 's/^[Ss]ecret:[[:space:]]*//')
CLIENT_ID=$(grep -iE '^Clien[dt]ID[[:space:]]*:' "$SECRETS_FILE" | head -1 | sed 's/^[Cc]lien[dt][Ii][Dd][[:space:]]*:[[:space:]]*//')

if [ -z "$CLIENT_SECRET" ]; then
    echo "[dstack-setup] ERROR: Could not parse 'Secret:' from $SECRETS_FILE" >&2
    exit 1
fi
if [ -z "$CLIENT_ID" ]; then
    echo "[dstack-setup] ERROR: Could not parse 'CliendID:' from $SECRETS_FILE" >&2
    exit 1
fi

mkdir -p "$DSTACK_CONFIG_DIR"

cat > "$DSTACK_CONFIG" <<EOF
# dstack server config — generated by dstack/setup-config.sh
# Re-run to update credentials.
projects:
  - name: main
    backends:
      - type: verda
        creds:
          type: api_key
          client_id: ${CLIENT_ID}
          client_secret: ${CLIENT_SECRET}
EOF

chmod 600 "$DSTACK_CONFIG"
echo "[dstack-setup] Written: $DSTACK_CONFIG (mode 600)"
echo "[STEP 4] dstack server config ready"
