#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="${1:-}"

if [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: dstack/scripts/render-pretrain-task.sh <output-file>" >&2
    exit 1
fi

if [ -z "${IMAGE_SHA:-}" ]; then
    echo "[render-pretrain-task] ERROR: IMAGE_SHA must be set" >&2
    exit 1
fi

TASK_NAME="${TASK_NAME:-verda-minimind-pretrain}"
TASK_BACKENDS="${TASK_BACKENDS:-}"
TASK_GPU_NAMES="${TASK_GPU_NAMES:-[H100, H200, A100]}"
TASK_GPU_COUNT="${TASK_GPU_COUNT:-1}"
TASK_SPOT_POLICY="${TASK_SPOT_POLICY:-spot}"
TASK_MAX_PRICE="${TASK_MAX_PRICE:-1.5}"
TASK_MAX_DURATION="${TASK_MAX_DURATION:-10m}"
TASK_IDLE_DURATION="${TASK_IDLE_DURATION:-0s}"
TASK_RETRY_DURATION="${TASK_RETRY_DURATION:-30m}"
TASK_REGIONS="${TASK_REGIONS:-}"
TASK_INSTANCE_TYPES="${TASK_INSTANCE_TYPES:-}"
TASK_MEMORY="${TASK_MEMORY:-1GB..}"
TASK_DISK="${TASK_DISK:-1GB..}"

# shellcheck source=training/scripts/lib/remote-env.sh
source "$REPO_ROOT/training/scripts/lib/remote-env.sh"
load_remote_env

# Only require VCR auth when using the Verda Container Registry.
# Public registries (Docker Hub, GHCR) don't need registry_auth.
if echo "${VCR_IMAGE_BASE:-}" | grep -q "vccr.io"; then
    require_vcr_auth
fi

umask 077
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Include registry_auth when using a private registry (VCR or Docker Hub with creds).
_REGISTRY_AUTH=""
if echo "${VCR_IMAGE_BASE:-}" | grep -q "vccr.io" && [ -n "${VCR_USERNAME:-}" ]; then
    _REGISTRY_AUTH="registry_auth:
  username: ${VCR_USERNAME}
  password: ${VCR_PASSWORD}"
elif [ -n "${DOCKER_USERNAME:-}" ] && [ -n "${DOCKER_PASSWORD:-}" ]; then
    _REGISTRY_AUTH="registry_auth:
  username: ${DOCKER_USERNAME}
  password: ${DOCKER_PASSWORD}"
fi

cat > "$OUTPUT_FILE" <<EOF
# generated by dstack/scripts/render-pretrain-task.sh — do not commit
type: task
name: ${TASK_NAME}

image: ${VCR_IMAGE_BASE}:${IMAGE_SHA}
${_REGISTRY_AUTH}

env:
  - HF_TOKEN
  - GPUPOOR_RUN_CONFIG_B64
  - MLFLOW_TRACKING_URI
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
  - AWS_DEFAULT_REGION
  - MLFLOW_S3_ENDPOINT_URL

commands:
  - bash /opt/training/scripts/remote-entrypoint.sh

${TASK_BACKENDS:+backends: ${TASK_BACKENDS}}
resources:
  memory: ${TASK_MEMORY}
  disk: ${TASK_DISK}
  gpu:
    name: ${TASK_GPU_NAMES}
    count: ${TASK_GPU_COUNT}

${TASK_REGIONS:+regions: ${TASK_REGIONS}}
${TASK_INSTANCE_TYPES:+instance_types: ${TASK_INSTANCE_TYPES}}
spot_policy: ${TASK_SPOT_POLICY}
max_price: ${TASK_MAX_PRICE}
max_duration: ${TASK_MAX_DURATION}
idle_duration: ${TASK_IDLE_DURATION}

retry:
  on_events:
    - no-capacity
    - interruption
  duration: ${TASK_RETRY_DURATION}
EOF

chmod 600 "$OUTPUT_FILE"
echo "$OUTPUT_FILE"
