#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="${1:-}"

if [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: dstack/scripts/render-pretrain-task.sh <output-file>" >&2
    exit 1
fi

if [ -z "${IMAGE_SHA:-}" ]; then
    echo "[render-pretrain-task] ERROR: IMAGE_SHA must be set" >&2
    exit 1
fi

# shellcheck source=training/scripts/lib/remote-env.sh
source "$REPO_ROOT/training/scripts/lib/remote-env.sh"
load_remote_env
require_vcr_auth

umask 077
mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
# generated by dstack/scripts/render-pretrain-task.sh — do not commit
type: task
name: verda-minimind-pretrain

image: ${VCR_IMAGE_BASE}:${IMAGE_SHA}
registry_auth:
  username: ${VCR_USERNAME}
  password: ${VCR_PASSWORD}

env:
  - HF_TOKEN
  - MLFLOW_TRACKING_URI
  - MLFLOW_EXPERIMENT_NAME=minimind-pretrain-remote
  - MLFLOW_ARTIFACT_UPLOAD=0
  - VERDA_PROFILE=remote
  - DSTACK_RUN_NAME=verda-minimind-pretrain
  - OUT_DIR=/workspace/out
  - HF_DATASET_REPO=jingyaogong/minimind_dataset
  - HF_DATASET_FILENAME=pretrain_t2t_mini.jsonl

commands:
  - bash /opt/training/scripts/remote-entrypoint.sh

resources:
  gpu:
    name: [H100, H200, A100]
    count: 1

spot_policy: spot
max_price: 1.5
max_duration: 10m
idle_duration: 0s

retry:
  on_events:
    - no-capacity
    - interruption
  duration: 30m
EOF

chmod 600 "$OUTPUT_FILE"
echo "$OUTPUT_FILE"
