#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="${1:-}"

if [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: dstack/scripts/render-pretrain-task.sh <output-file>" >&2
    exit 1
fi

if [ -z "${IMAGE_SHA:-}" ]; then
    echo "[render-pretrain-task] ERROR: IMAGE_SHA must be set" >&2
    exit 1
fi

TASK_NAME="${TASK_NAME:-verda-minimind-pretrain}"
TASK_GPU_NAMES="${TASK_GPU_NAMES:-[H100, H200, A100]}"
TASK_GPU_COUNT="${TASK_GPU_COUNT:-1}"
TASK_SPOT_POLICY="${TASK_SPOT_POLICY:-spot}"
TASK_MAX_PRICE="${TASK_MAX_PRICE:-1.5}"
TASK_MAX_DURATION="${TASK_MAX_DURATION:-10m}"
TASK_IDLE_DURATION="${TASK_IDLE_DURATION:-0s}"
TASK_RETRY_DURATION="${TASK_RETRY_DURATION:-30m}"
TASK_REGIONS="${TASK_REGIONS:-}"
TASK_INSTANCE_TYPES="${TASK_INSTANCE_TYPES:-}"

# shellcheck source=training/scripts/lib/remote-env.sh
source "$REPO_ROOT/training/scripts/lib/remote-env.sh"
load_remote_env
require_vcr_auth

umask 077
mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
# generated by dstack/scripts/render-pretrain-task.sh — do not commit
type: task
name: ${TASK_NAME}

image: ${VCR_IMAGE_BASE}:${IMAGE_SHA}
registry_auth:
  username: ${VCR_USERNAME}
  password: ${VCR_PASSWORD}

env:
  - HF_TOKEN
  - MLFLOW_TRACKING_URI
  - MLFLOW_EXPERIMENT_NAME
  - MLFLOW_ARTIFACT_UPLOAD
  - MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING
  - MLFLOW_SYSTEM_METRICS_SAMPLING_INTERVAL
  - MLFLOW_SYSTEM_METRICS_SAMPLES_BEFORE_LOGGING
  - MLFLOW_HTTP_REQUEST_MAX_RETRIES
  - MLFLOW_HTTP_REQUEST_TIMEOUT
  - MLFLOW_START_TIMEOUT_SECONDS
  - MLFLOW_START_RETRY_SECONDS
  - MLFLOW_PEAK_TFLOPS_PER_GPU
  - MLFLOW_TIME_TO_TARGET_METRIC
  - MLFLOW_TIME_TO_TARGET_VALUE
  - VERDA_PROFILE
  - DSTACK_RUN_NAME
  - OUT_DIR
  - HF_DATASET_REPO
  - HF_DATASET_FILENAME
  - HF_PRETOKENIZED_DATASET_REPO
  - HF_PRETOKENIZED_DATASET_FILENAME
  - TIME_CAP_SECONDS
  - VALIDATION_SPLIT_RATIO
  - VALIDATION_INTERVAL_STEPS

commands:
  - bash /opt/training/scripts/remote-entrypoint.sh

resources:
  gpu:
    name: ${TASK_GPU_NAMES}
    count: ${TASK_GPU_COUNT}

${TASK_REGIONS:+regions: ${TASK_REGIONS}}
${TASK_INSTANCE_TYPES:+instance_types: ${TASK_INSTANCE_TYPES}}
spot_policy: ${TASK_SPOT_POLICY}
max_price: ${TASK_MAX_PRICE}
max_duration: ${TASK_MAX_DURATION}
idle_duration: ${TASK_IDLE_DURATION}

retry:
  on_events:
    - no-capacity
    - interruption
  duration: ${TASK_RETRY_DURATION}
EOF

chmod 600 "$OUTPUT_FILE"
echo "$OUTPUT_FILE"
