#!/bin/bash
# dstack/scripts/setup-config.sh — write ~/.dstack/server/config.yml with repo backends
#
# Reads ./secrets for CliendID (note typo) and Secret.
# Idempotent: safe to run multiple times.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SECRETS_FILE="$REPO_ROOT/secrets"
RUNPOD_KEY_FILE="$REPO_ROOT/infrastructure/capacity-seeker/runpod_api_key"
VASTAI_KEY_FILE="$REPO_ROOT/infrastructure/capacity-seeker/vastai_api_key"
DSTACK_CONFIG_DIR="$HOME/.dstack/server"
DSTACK_CONFIG="$DSTACK_CONFIG_DIR/config.yml"
DSTACK_RESTART_MARKER="$DSTACK_CONFIG_DIR/.restart-required"

echo "[STEP 4] Configuring dstack server with Verda backend..."

configured_backends=("verda")

resolve_optional_key_file() {
    local primary="$1"
    shift
    if [ -f "$primary" ]; then
        printf '%s' "$primary"
        return 0
    fi
    local candidate
    for candidate in "$@"; do
        if [ -f "$candidate" ]; then
            printf '%s' "$candidate"
            return 0
        fi
    done
    printf '%s' "$primary"
}

read_api_key_file() {
    local key_file="$1"
    if [ ! -f "$key_file" ]; then
        return 0
    fi

    python - "$key_file" <<'PY'
from pathlib import Path
import re
import sys

text = Path(sys.argv[1]).read_text(encoding="utf-8").strip()
if not text:
    raise SystemExit(0)

line = next((part.strip() for part in text.splitlines() if part.strip()), "")
if not line:
    raise SystemExit(0)

if "=" in line:
    _, line = line.split("=", 1)
elif ":" in line:
    _, line = line.split(":", 1)

line = line.strip().strip("'\"")
line = re.sub(r"\s+", "", line)
print(line, end="")
PY
}

VASTAI_KEY_FILE="$(resolve_optional_key_file \
    "$VASTAI_KEY_FILE" \
    "$REPO_ROOT/infrastructure/capacity-seeker/vast_ai_key" \
    "$REPO_ROOT/infrastructure/capacity-seeker/vast_ai_api_key" \
    "$REPO_ROOT/infrastructure/capacity-seeker/vast_api_key")"

if [ ! -f "$SECRETS_FILE" ]; then
    echo "[dstack-setup] ERROR: $SECRETS_FILE not found" >&2
    exit 1
fi

# Parse secrets — handle "CliendID" typo as well as "ClientID"
# Format:
#   Secret: <value>
#   CliendID : <value>   (note typo in Verda UI)
CLIENT_SECRET=$(grep -i '^Secret:' "$SECRETS_FILE" | head -1 | sed 's/^[Ss]ecret:[[:space:]]*//')
CLIENT_ID=$(grep -iE '^Clien[dt]ID[[:space:]]*:' "$SECRETS_FILE" | head -1 | sed 's/^[Cc]lien[dt][Ii][Dd][[:space:]]*:[[:space:]]*//')

if [ -z "$CLIENT_SECRET" ]; then
    echo "[dstack-setup] ERROR: Could not parse 'Secret:' from $SECRETS_FILE" >&2
    exit 1
fi
if [ -z "$CLIENT_ID" ]; then
    echo "[dstack-setup] ERROR: Could not parse 'CliendID:' from $SECRETS_FILE" >&2
    exit 1
fi

mkdir -p "$DSTACK_CONFIG_DIR"

tmp_config="$(mktemp "$DSTACK_CONFIG_DIR/config.yml.tmp.XXXXXX")"

cat > "$tmp_config" <<EOF
# dstack server config — generated by dstack/scripts/setup-config.sh
# Re-run to update credentials.
projects:
  - name: main
    backends:
      - type: verda
        creds:
          type: api_key
          client_id: ${CLIENT_ID}
          client_secret: ${CLIENT_SECRET}
EOF

if [ -f "$RUNPOD_KEY_FILE" ]; then
    RUNPOD_API_KEY="$(read_api_key_file "$RUNPOD_KEY_FILE")"
    if [ -n "$RUNPOD_API_KEY" ]; then
        cat >> "$tmp_config" <<EOF
      - type: runpod
        creds:
          type: api_key
          api_key: ${RUNPOD_API_KEY}
EOF
        configured_backends+=("runpod")
        echo "[dstack-setup] Enabled optional backend: runpod"
    else
        echo "[dstack-setup] Skipping optional backend runpod: $RUNPOD_KEY_FILE is empty or invalid"
    fi
else
    echo "[dstack-setup] Skipping optional backend runpod: $RUNPOD_KEY_FILE is missing"
fi

if [ -f "$VASTAI_KEY_FILE" ]; then
    VASTAI_API_KEY="$(read_api_key_file "$VASTAI_KEY_FILE")"
    if [ -n "$VASTAI_API_KEY" ]; then
        cat >> "$tmp_config" <<EOF
      - type: vastai
        creds:
          type: api_key
          api_key: ${VASTAI_API_KEY}
EOF
        configured_backends+=("vastai")
        echo "[dstack-setup] Enabled optional backend: vastai"
    else
        echo "[dstack-setup] Skipping optional backend vastai: $VASTAI_KEY_FILE is empty or invalid"
    fi
else
    echo "[dstack-setup] Skipping optional backend vastai: $VASTAI_KEY_FILE is missing"
fi

if [ ! -f "$DSTACK_CONFIG" ] || ! cmp -s "$tmp_config" "$DSTACK_CONFIG"; then
    mv "$tmp_config" "$DSTACK_CONFIG"
    touch "$DSTACK_RESTART_MARKER"
else
    rm -f "$tmp_config"
fi

chmod 600 "$DSTACK_CONFIG"
echo "[dstack-setup] Written: $DSTACK_CONFIG (mode 600)"
echo "[dstack-setup] Configured backends: ${configured_backends[*]}"
echo "[STEP 4] dstack server config ready"
